version: "3"
services:
  proxy:
    image: ubuntu/squid
    ports:
      - "8080:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    restart: always
    logging:
      driver: syslog 
      options:
        syslog-address: "udp://10.1.0.94:514"
        syslog-facility: "local7"
        tag: "squid-proxy0"
